### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by DanDanTheManDan** [Ciantic/DisableFlashingTaskbarButtons#3]
Hi,

I LOVE this software. It really saved me a lot of rage at Windows total lack of empowerment of the user to have a say over when an app can interrupt and distract you.

I downloaded it a few months ago and set it to run at startup. Worked great. However, as of maybe a month ago, it stopped working. Maybe due to a Microsoft update?

I get the following error message now when running it: 
![image](https://user-images.githubusercontent.com/42029104/43578750-53daa830-9682-11e8-8f29-bcafb4addf86.png)

Of course, I'm not paying anything for this great script. But if the developer was to upgrade it, it would really make my life a lot nicer! Thanks.

**Comment by Ciantic** [comment]
Yup, I noticed this. I'm going to fix this when I have time. 

Since the last Windows update, there is no more space above the patched function in the explorer.exe memory so I have to come up a new way to patch this.

Btw, I don't understand why Microsoft does not give us a simple switch to turn these flashing taskbar buttons off, they are annoying. There is freaking notification center, at least it can be muted, but this can't be.

**Comment by Ciantic** [comment]
Works again! Got the 1809 working in Hyper-V so I could fix this.

**Comment by DanDanTheManDan** [comment]
For some reason, didn't work the first time I tried. Recently tried again, now it works. You have markedly improved my quality of life. Thank you.
